= Pflichtenheft - Car Go
firstname lastname
1.0.0, yyyy-mm-dd
:sourcedir: ../src/main/java
ifndef::imagesdir[:imagesdir: images]
ifndef::backend[:backend: html5]
:icons: font
:toc: left

== Ausgangssituation

Die HTL Leonding ist eine Höhere Technische Lehranstalt in Oberösterreich. In Zuge
der Ausbildung müssen die Schüler Projekte umsetzen.

== Istzustand

Es sind mehrere Roboterfahrzeuge vorhanden, welche seit längerer Zeit außer Betrieb sind.
Vor drei Jahren wurden sie von ehemaligen Drittklasslern aus dem Informatik Zweig programmiert.

=== Aktivitäten
Diagramm 1: Steuerung
[plantuml,activityDiagram1,png]
--
@startuml
|FahrerIn|
start
:Aktiviert Auto;
:Startet Client;
:Stellt Serververbindung her;
|Client|
while(Verbindung steht?)
|FahrerIn|
:Gibt die Fahrtrichtung an;
|Client|
:Interpretiert Befehl;
|Server|
:Führt Befehl aus;
endwhile
|Client|
:Abbruch;
stop
@enduml
--

Diagramm 2: Kameraübertragung
[plantuml,activityDiagram1,png, id="activityTwo", width="600px", height="200px"]
--
@startuml
|FahrerIn|
start
:Öffnet Browserfenster;
:Tippt IP-Adresse in die Suchleiste ein;
|Client|
while(Seite geöffnet?)
:Schickt Anfrage an den Server;
|Server|
:Verwertet die Kameraaufzeichnung;
:Schickt Aufzeichnung an den Client;
|Client|
:Zeigt erhaltene Aufnahmen an;
endwhile
:Abbruch;
stop
@enduml
--

== Problemstellung

Die Autos sind außer Betrieb und lassen sich nicht steuern.

== Aufgabenstellung

=== Funktionale Anforderungen

==== Anwendungsfalldiagramm (Use-Case-Diagram)

[plantuml,usecase1,png, id="useCase", width="600px", height="200px"]
--
@startuml
left to right direction
skinparam packageStyle rectangle
actor FahrerIn
actor Fahrzeug
actor Bildschirm
rectangle Autokommunikation {
    FahrerIn -- (Fahrzeug lenken)
    (Fahrzeug lenken) -- Fahrzeug
    (Kameraübetragung) -- Fahrzeug
    Bildschirm -- (Kameraübetragung)
}
@enduml
--

===== Use-Case

===== Charakterisierende Informationen Use-Case

[cols=2]
|===
| Übergeordneter elementarer Geschäftsprozess:
| Die Benutzer wollen die Autos steuern und wählen eine Steuerung nach Wahl. Anschließend stellen Sie eine Verbinndung mit den Sever über den Client her. Die Fahrzeuge sind nun steuerbereit.
| Ziel des Use Cases:
| Das Use Case sollten den Benutzer aufklären, wie man mit den Auto kommunizieren kann.

| Umgebende Systemgrenze:
| Ein auf den Autos laufender Server reagiert auf den Client.

| Vorbedingung:
| Der Server muss jeweils auf den Autos laufen um eine Verbindung zwischen ihm und den Client zu gewährleisten.

| Nachbedingung bei erfolgreicher Ausführung:
| Das Auto reagiert auf die Steuerung und folgedessen fährt das Auto.

| Beschreibung:
a|
* Art der Steurung wählen
* als Client die Verbindung mit den Server aufbauen
* Autos steuern/lenken

| Beteiligte Nutzer:
| AutofahrerIn

| Auslösendes Ereignis:
| Imput des Client (Steuerung nutzen)
|===

===== GUI für den Aufruf des Use-Case


==== Nicht-funktionale Anforderungen

Typen von Produktcharakteristiken

Typ USE: 		Benutzbarkeitsanforderung


Die in Abschnitt 1 beschriebene Zielgruppe liegt diesen Anforderungen zugrunde. Wie muß die Software beschaffen sein, damit diese Zielgruppe gerne damit arbeitet?
Beispiel: Die Software soll flexibel für unterschiedliche Arbeitsweisen einsetzbar sein.
ODER
Die Software soll dem Erscheinungsbild anderer Produkte des Herstellers
entsprechen.

Das GUI sollte für den Client einfache gestalltet sein, sodass schnelle inbetriebnahmen vorhanden ist.


Typ EFFIZIENZ: 	Effizienzanforderung

Hier geht es sowohl um Laufzeit- als auch um Speichereffizienz. Was wird unter dem sparsamen Einsatz dieser Ressourcen verstanden?
Beispiel: Die Berechnung darf nicht länger als 0,25 Sekunden dauern.

Zwischen Eingabe des Clients und Ausführung des Servers darf es keine zu hohe Latenz geben.

Typ PFLEGE:	Wartbarkeits- und Portierbarkeitsanforderung

Welcher Grad an Änderbarkeit wird gefordert? Hier werden, soweit wie möglich, kommende Anpassungen und Erweiterungen vorhergesehen.
Beispiel: Das Produkt soll später auch in englischer Sprache verfügbar sein.

Der Anwendungsfall der Autos würde sich in der Zukunft nicht nur auf die Steuerung fokusieren, sondern könnte auch Bilder übertragen oder Musik abspielen.

Typ SICHER:	Sicherheitsanforderung

Zu den Sicherheitsanforderungen gehören die Aspekte Vertraulichkeit, Datenintegrität und Verfügbarkeit. Wie sehr müssen die Daten vor dem Zugriff durch Dritte geschützt werden? Ist es entscheidend, die Korrektheit der erfassten Daten und ihre Konsistenz zu gewährleisten? Dürfen Systemausfälle vorkommen?
Beispiel: Das System muss gewährleisten, dass Daten nie verändert werden können.

Die Autos müssen in einen abgesicherten Bereich agieren, sodass man keine "Verkehrsbedrohung" darstellt und unter anderem nicht die Verbindung verloren geht.


== Zielsetzung

Besucher sollen am Tag der offenen Tür mit den Roboterfahrzeugen den Roboterführerschein machen können.


== Gantt-Chart

[plantuml,gantt1,png,id="ganttChart1", width="800px", height="200px"]
--
@startuml
project starts the 2018/10/14
2019/12/21 to 2020/01/05 is closed
[Setup Analyze] lasts 10 days
[Hotspot Configuration] lasts 28 days
[Server Connection] lasts 10 days
[Error Search] lasts 4 days
[Hotspot Configuration] starts at [Setup Analyze]'s end
[Server Connection] starts at [Hotspot Configuration]'s end
[Error Search] starts at [Server Connection]'s end

@enduml
--

[plantuml,gantt2,png, id="ganttChart2", width="800px", height="200px"]
--
@startuml
project starts the 2020/01/06
2020/01/25 to 2020/02/11 is closed
[Open House Day Preparation] lasts 19 days
[Specification] lasts 1 day
[Specification] starts the 2020/02/12

@enduml
--

[plantuml,gantt3,png, id="ganttChart3", width="800px", height="200px"]
--
@startuml
project starts the 2020/03/09
2020/03/31 to 2020/04/17 is closed
[Github Repo Management] lasts 21 days
[Github Pages] lasts 3 days
[Specification] lasts 3 days
[Github Pages] starts the 2020/03/27
[Specification] starts the 2020/03/27
[Project Documentation] starts the 2020/04/18

@enduml
--

== User-Stories

- Als User möchte ich das Roboterfahrzeug mit dem Joystick bedienen können,
um ein besseres Gefühl für die Steuerung zu bekommen, als mit einer
Computertastatur.

- Als User möchte ich das Roboterfahrzeug mit einer Tanzmatte steuern können,
falls eines der Autos (am Tag der öffenen Tür) schon mit dem Joystick bedient wird.

- Als User möchte ich am PC sehen können, was die Kamera überträgt.
So kann ich sehen, wohin das Fahrzeug fährt, auch wenn es z.B. durch
einen Tunnel fährt.
